"""
EN

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

TR

Fibonacci serisinde her sayı, kendisinden önce gelen iki sayının toplamıdır. 1 ve 2 ile başlayan serinin ilk 10 sayısı:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Bu serinin dört milyondan küçük tüm çift sayılarının toplamını bulunuz.

"""


#!/usr/bin/python
liste=[]
top=0
a,b=0,1
while b<4000000:
    if b%2==0:
        liste.append(b)
        print (b)

    a,b=b,a+b

print liste

for i in liste:
    top+=int(i)

print  top
